#+title: HLT emulation


* About

When conducting trigger studies, we are often working with development menus that contain trigger paths not included in the official menus.  These development menus will not be processed by default in the foresting process, which only processes the official HLT working menu.  Thus we must run HLT emulation, which inputs DIGIRAW data and processes custom HLT paths.  With the code in this repo, one can input an HLT trigger path and dataset and process the HLT trigger decisions, which can then be used in efficiency studies.

Relevant variables to edit:

| variable        | default                                                                                                                                            |
|-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------|
| ~TRIGGERMENU~   | ~/users/cbennett/151X/HLT_jetTriggers_HIon_2025/V7~                                                                                                |
| ~GLOBALTAG~     | ~151X_mcRun3_2025_realistic_HI_v1~                                                                                                                 |
| ~L1MENU~        | ~L1Menu_CollisionsHeavyIons2025_v1_0_1.xml~                                                                                                        |
| ~ERA~           | ~Run3_pp_on_PbPb_2025~                                                                                                                             |
| ~INPUT_DATASET~ | ~/Dijet_pTHatMin15_HydjetEmbedded_Pythia8_TuneCP5_1510pre6/fdamas-DIGIRAWHLT_151X_mcRun3_2025_realistic_HI_v1-cbd44d18142345ebc4de72df33778d6f/USER~ |
|                 |                                                                                                                                                    |

* Instructions

Retrieve the ~setup_CMSSW.sh~ script to configure working environment:

#+begin_src sh
  wget https://raw.githubusercontent.com/claytoniousfunk/HLT_emulation/refs/heads/main/scripts/setup_CMSSW/setup_CMSSW_151X.sh
#+end_src

Enable permissions to execute:

#+begin_src sh
  chmod +x setup_CMSSW_151X.sh
#+end_src

Run the script:

#+begin_src sh
  ./setup_CMSSW_151X.sh
#+end_src

Move into the new CMSSW and initialize:

#+begin_src sh
  cd CMSSW_15_1_0_pre6/src/workstation
  cmsenv
#+end_src

Clone the git repo and move into the PbPb directory:

#+begin_src sh
  git clone git@github.com:claytoniousfunk/HLT_emulation.git
  cd HLT_emulation/scripts/PbPb
#+end_src

Run the emulation script:

#+begin_src sh
  ./emulate_HLT_HIon_2025.sh 1 2
#+end_src

The arguments ~1~ and ~2~ indicate the ~start_index~ and ~end_index~ of the input file list.

The output will be a file named ~openHLT_i.root~ where ~i={1,2,...,N}~ is the index corresponding to an input file on the file list.  This ~openHLT_i.root~ file contains the HLT trigger decisions for the processed events.
